import { useEffect, useState, useMemo } from "react";
import "./App.css";

const API_BASE = "http://localhost:5000/api/recipe";

// Utility to format MongoDB ISO dates cleanly
function formatRecipeDate(dateString) {
  if (!dateString) return "Recently";
  try {
    const date = new Date(dateString);
    if (isNaN(date.getTime())) return "Recently";
    return new Intl.DateTimeFormat("en-US", {
      month: "short",
      day: "numeric",
      year: "numeric",
    }).format(date);
  } catch {
    return "Recently";
  }
}

// Format full recipe as clean text for clipboard
function formatRecipeForCopy(r) {
  const parts = [];
  parts.push(`🍳 ${r.name.toUpperCase()}`);
  if (r.description) parts.push(`\n${r.description}`);
  parts.push(`\n⏱️ Prep: ${r.prepTime || "N/A"} | Cook: ${r.cookTime || "N/A"} | Servings: ${r.servings || "N/A"} | Difficulty: ${r.difficulty || "N/A"}`);
  
  if (r.ingredients?.length) {
    parts.push("\n🛒 INGREDIENTS:");
    r.ingredients.forEach((ing) => parts.push(`  • ${ing}`));
  }
  
  if (r.instructions?.length) {
    parts.push("\n👨‍🍳 INSTRUCTIONS:");
    r.instructions.forEach((step, idx) => parts.push(`  ${idx + 1}. ${step}`));
  }
  
  if (r.tips?.length) {
    parts.push("\n💡 CHEF'S TIPS:");
    r.tips.forEach((tip) => parts.push(`  • ${tip}`));
  }

  parts.push("\n— Generated by RecipeAI");
  return parts.join("\n");
}

function App() {
  // Existing state
  const [dish, setDish] = useState("");
  const [recipe, setRecipe] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [savedRecipes, setSavedRecipes] = useState([]);

  // New state
  const [savedLoading, setSavedLoading] = useState(true);
  const [fetchError, setFetchError] = useState("");
  const [searchQuery, setSearchQuery] = useState("");
  const [filterMode, setFilterMode] = useState("all"); // "all" | "favorites"
  const [selectedRecipe, setSelectedRecipe] = useState(null);
  const [deleteConfirmId, setDeleteConfirmId] = useState(null);
  const [isDeleting, setIsDeleting] = useState(false);
  const [toastMessage, setToastMessage] = useState("");
  const [copiedId, setCopiedId] = useState(null);

  // Theme state
  const [theme, setTheme] = useState(() => {
    const savedTheme = localStorage.getItem("recipeai_theme");
    if (savedTheme) return savedTheme;
    return window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches
      ? "dark"
      : "light";
  });

  // Apply theme to document element and persist in localStorage
  useEffect(() => {
    document.documentElement.setAttribute("data-theme", theme);
    localStorage.setItem("recipeai_theme", theme);
  }, [theme]);

  const toggleTheme = () => {
    setTheme((prev) => (prev === "dark" ? "light" : "dark"));
  };

  // Toast notification helper
  const showToast = (msg) => {
    setToastMessage(msg);
    setTimeout(() => {
      setToastMessage((current) => (current === msg ? "" : current));
    }, 3000);
  };

  // Fetch saved recipes from MongoDB
  const fetchSavedRecipes = async () => {
    setSavedLoading(true);
    setFetchError("");
    try {
      const response = await fetch(API_BASE);
      const data = await response.json();

      if (data.success) {
        setSavedRecipes(data.recipes || []);
      } else {
        setFetchError(data.message || "Failed to load saved recipes.");
      }
    } catch (err) {
      console.error("Unable to fetch saved recipes:", err);
      setFetchError("Unable to connect to the backend server.");
    } finally {
      setSavedLoading(false);
    }
  };

  useEffect(() => {
    let ignore = false;

    const loadInitialData = async () => {
      try {
        const response = await fetch(API_BASE);
        const data = await response.json();

        if (!ignore) {
          if (data.success) {
            setSavedRecipes(data.recipes || []);
          } else {
            setFetchError(data.message || "Failed to load saved recipes.");
          }
        }
      } catch (err) {
        if (!ignore) {
          console.error("Unable to fetch saved recipes:", err);
          setFetchError("Unable to connect to the backend server.");
        }
      } finally {
        if (!ignore) {
          setSavedLoading(false);
        }
      }
    };

    loadInitialData();

    return () => {
      ignore = true;
    };
  }, []);

  // Keyboard navigation for Modal (ESC key)
  useEffect(() => {
    const handleKeyDown = (e) => {
      if (e.key === "Escape") {
        if (deleteConfirmId) {
          setDeleteConfirmId(null);
        } else if (selectedRecipe) {
          setSelectedRecipe(null);
        }
      }
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [selectedRecipe, deleteConfirmId]);

  // Generate recipe via Gemini AI
  const generateRecipe = async (overrideDish) => {
    const targetDish = (typeof overrideDish === "string" ? overrideDish : dish).trim();

    if (!targetDish) {
      setError("Please enter a dish name first.");
      return;
    }

    setLoading(true);
    setError("");
    setRecipe(null);

    try {
      const response = await fetch(API_BASE, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          dish: targetDish,
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.message || "Something went wrong.");
      }

      setRecipe(data.recipe);

      // Automatically add new recipe to the saved recipes history list
      if (data.recipe) {
        setSavedRecipes((prev) => {
          const exists = prev.some((r) => r._id === data.recipe._id);
          return exists ? prev : [data.recipe, ...prev];
        });
      }

      // Scroll to generated recipe smoothly
      setTimeout(() => {
        const el = document.getElementById("generated-recipe-anchor");
        if (el) el.scrollIntoView({ behavior: "smooth" });
      }, 100);
    } catch (err) {
      console.error("Generate recipe error:", err);
      setError("Unable to generate the recipe right now. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  // Toggle favorite
  const handleToggleFavorite = async (e, recipeItem) => {
    if (e && e.stopPropagation) e.stopPropagation();
    const recipeId = recipeItem._id;

    // Optimistic UI update
    setSavedRecipes((prev) =>
      prev.map((r) =>
        r._id === recipeId ? { ...r, isFavorite: !r.isFavorite } : r
      )
    );

    if (selectedRecipe && selectedRecipe._id === recipeId) {
      setSelectedRecipe((prev) => ({ ...prev, isFavorite: !prev.isFavorite }));
    }

    if (recipe && recipe._id === recipeId) {
      setRecipe((prev) => ({ ...prev, isFavorite: !prev.isFavorite }));
    }

    try {
      const res = await fetch(`${API_BASE}/${recipeId}/favorite`, {
        method: "PATCH",
      });
      const data = await res.json();
      if (!res.ok || !data.success) {
        // Revert if error
        setSavedRecipes((prev) =>
          prev.map((r) =>
            r._id === recipeId ? { ...r, isFavorite: recipeItem.isFavorite } : r
          )
        );
        showToast("Could not update favorite status.");
      } else {
        showToast(
          data.recipe?.isFavorite ? "Added to Favorites ❤️" : "Removed from Favorites"
        );
      }
    } catch (err) {
      console.error("Favorite toggle error:", err);
      // Revert on failure
      setSavedRecipes((prev) =>
        prev.map((r) =>
          r._id === recipeId ? { ...r, isFavorite: recipeItem.isFavorite } : r
        )
      );
      showToast("Unable to reach server to update favorite.");
    }
  };

  // Delete recipe
  const handleDeleteRecipe = async (recipeId) => {
    setIsDeleting(true);
    try {
      const res = await fetch(`${API_BASE}/${recipeId}`, {
        method: "DELETE",
      });
      const data = await res.json();

      if (!res.ok || !data.success) {
        throw new Error(data.message || "Failed to delete recipe.");
      }

      // Immediately remove from list without page refresh
      setSavedRecipes((prev) => prev.filter((r) => r._id !== recipeId));

      if (selectedRecipe && selectedRecipe._id === recipeId) {
        setSelectedRecipe(null);
      }
      if (recipe && recipe._id === recipeId) {
        setRecipe(null);
      }

      setDeleteConfirmId(null);
      showToast("Recipe deleted successfully.");
    } catch (err) {
      console.error("Delete error:", err);
      showToast("Failed to delete recipe. Please try again.");
    } finally {
      setIsDeleting(false);
    }
  };

  // Copy recipe
  const handleCopyRecipe = async (e, r) => {
    if (e && e.stopPropagation) e.stopPropagation();
    try {
      const text = formatRecipeForCopy(r);
      await navigator.clipboard.writeText(text);
      setCopiedId(r._id || "current");
      showToast("Recipe copied to clipboard! 📋");
      setTimeout(() => {
        setCopiedId(null);
      }, 2500);
    } catch (err) {
      console.error("Clipboard copy error:", err);
      showToast("Could not copy recipe to clipboard.");
    }
  };

  // Print recipe
  const handlePrintRecipe = (e, r) => {
    if (e && e.stopPropagation) e.stopPropagation();
    // Ensure the recipe to print is in view
    if (!selectedRecipe || selectedRecipe._id !== r._id) {
      setSelectedRecipe(r);
    }
    setTimeout(() => {
      window.print();
    }, 150);
  };

  // Filtered & Searched recipes
  const filteredRecipes = useMemo(() => {
    let list = savedRecipes;

    if (filterMode === "favorites") {
      list = list.filter((r) => r.isFavorite);
    }

    if (searchQuery.trim()) {
      const q = searchQuery.toLowerCase().trim();
      list = list.filter(
        (r) =>
          r.name?.toLowerCase().includes(q) ||
          r.description?.toLowerCase().includes(q)
      );
    }

    return list;
  }, [savedRecipes, filterMode, searchQuery]);

  const favoritesCount = useMemo(() => {
    return savedRecipes.filter((r) => r.isFavorite).length;
  }, [savedRecipes]);

  // Quick dish inspiration suggestions
  const suggestions = [
    "Creamy Tuscan Chicken",
    "Spicy Garlic Ramen",
    "Classic Margherita Pizza",
    "Chocolate Molten Lava Cake",
    "Thai Green Curry",
  ];

  return (
    <div className="app">
      {/* Toast Notification */}
      {toastMessage && (
        <div className="toast-notification" role="status" aria-live="polite">
          <span>{toastMessage}</span>
        </div>
      )}

      {/* NAVBAR */}
      <nav className="navbar">
        <div className="logo" onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}>
          <span className="logo-icon">🍳</span>
          <span className="logo-text">
            Recipe<span>AI</span>
          </span>
        </div>

        <div className="nav-center">
          <a href="#home">Home</a>
          <a href="#generator">Create</a>
          <a href="#saved-recipes">
            Saved History
            {savedRecipes.length > 0 && (
              <span className="nav-badge">{savedRecipes.length}</span>
            )}
          </a>
        </div>

        <div className="nav-actions">
          <button
            className="theme-toggle-btn"
            onClick={toggleTheme}
            aria-label={`Switch to ${theme === "dark" ? "light" : "dark"} mode`}
            title={`Switch to ${theme === "dark" ? "light" : "dark"} mode`}
          >
            {theme === "dark" ? (
              <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <circle cx="12" cy="12" r="5"></circle>
                <line x1="12" y1="1" x2="12" y2="3"></line>
                <line x1="12" y1="21" x2="12" y2="23"></line>
                <line x1="4.22" y1="4.22" x2="5.64" y2="5.64"></line>
                <line x1="18.36" y1="18.36" x2="19.78" y2="19.78"></line>
                <line x1="1" y1="12" x2="3" y2="12"></line>
                <line x1="21" y1="12" x2="23" y2="12"></line>
                <line x1="4.22" y1="19.78" x2="5.64" y2="18.36"></line>
                <line x1="18.36" y1="5.64" x2="19.78" y2="4.22"></line>
              </svg>
            ) : (
              <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"></path>
              </svg>
            )}
            <span className="theme-toggle-label">{theme === "dark" ? "Light" : "Dark"}</span>
          </button>
        </div>
      </nav>

      <main>
        {/* HERO */}
        <section className="hero" id="home">
          <div className="hero-content">
            <div className="eyebrow-badge">
              <span className="sparkle">✨</span>
              <span>AI-POWERED RECIPE GENERATOR</span>
            </div>

            <h1>
              Create Delicious
              <br />
              <span className="gradient-text">Recipes with AI</span>
            </h1>

            <p className="hero-text">
              Enter any dish, ingredient, or craving. Our intelligent culinary assistant
              will formulate complete, step-by-step chef recipes in seconds.
            </p>

            {/* GENERATOR CARD */}
            <div className="generator-card" id="generator">
              <div className="input-wrapper">
                <div className="input-field-container">
                  <svg className="search-dish-icon" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <circle cx="11" cy="11" r="8"></circle>
                    <line x1="21" y1="21" x2="16.65" y2="16.65"></line>
                  </svg>
                  <input
                    type="text"
                    value={dish}
                    onChange={(e) => setDish(e.target.value)}
                    onKeyDown={(e) => {
                      if (e.key === "Enter" && !loading) {
                        generateRecipe();
                      }
                    }}
                    placeholder="e.g. Chicken Biryani, Creamy Alfredo, Chocolate Lava Cake..."
                    disabled={loading}
                    autoComplete="off"
                  />
                  {dish && (
                    <button
                      className="clear-input-btn"
                      onClick={() => setDish("")}
                      title="Clear dish name"
                      aria-label="Clear dish name"
                    >
                      ✕
                    </button>
                  )}
                </div>

                <button
                  className="generate-button"
                  onClick={() => generateRecipe()}
                  disabled={loading || !dish.trim()}
                >
                  {loading ? (
                    <>
                      <span className="btn-spinner"></span>
                      <span>Creating Recipe...</span>
                    </>
                  ) : (
                    <>
                      <span>Generate Recipe</span>
                      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                        <line x1="5" y1="12" x2="19" y2="12"></line>
                        <polyline points="12 5 19 12 12 19"></polyline>
                      </svg>
                    </>
                  )}
                </button>
              </div>

              {error && (
                <div className="error-banner">
                  <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <circle cx="12" cy="12" r="10"></circle>
                    <line x1="12" y1="8" x2="12" y2="12"></line>
                    <line x1="12" y1="16" x2="12.01" y2="16"></line>
                  </svg>
                  <span>{error}</span>
                </div>
              )}

              {/* Suggestions Chips */}
              <div className="suggestions-container">
                <span className="suggestions-label">Try asking for:</span>
                <div className="suggestions-list">
                  {suggestions.map((item, idx) => (
                    <button
                      key={idx}
                      type="button"
                      className="suggestion-chip"
                      onClick={() => {
                        setDish(item);
                        generateRecipe(item);
                      }}
                      disabled={loading}
                    >
                      {item}
                    </button>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* LOADING ANIMATION */}
        {loading && (
          <section className="loading-section" aria-live="polite">
            <div className="loading-card">
              <div className="cooking-pot-animation">
                <span className="bubble b1">🥘</span>
                <span className="bubble b2">✨</span>
                <span className="bubble b3">🌿</span>
              </div>
              <div className="spinner-ring"></div>
              <h2>Chef AI is cooking...</h2>
              <p>Formulating ingredients, calculating cooking times, and perfecting instructions for you.</p>
              <div className="loading-progress-bar">
                <div className="loading-progress-fill"></div>
              </div>
            </div>
          </section>
        )}

        {/* CURRENTLY GENERATED RECIPE SECTION */}
        <div id="generated-recipe-anchor"></div>
        {recipe && !loading && (
          <section className="recipe-section">
            <div className="recipe-card" id="recipe-print-area">
              {/* Card Action Bar */}
              <div className="card-top-actions">
                <div className="recipe-badge-group">
                  <span className="recipe-label">AI-GENERATED RECIPE</span>
                  {recipe.difficulty && (
                    <span className={`difficulty-tag difficulty-${recipe.difficulty.toLowerCase()}`}>
                      {recipe.difficulty}
                    </span>
                  )}
                </div>

                <div className="action-buttons-group">
                  <button
                    className={`icon-action-btn favorite-btn ${recipe.isFavorite ? "active" : ""}`}
                    onClick={(e) => handleToggleFavorite(e, recipe)}
                    title={recipe.isFavorite ? "Remove from favorites" : "Save to favorites"}
                  >
                    <svg width="20" height="20" viewBox="0 0 24 24" fill={recipe.isFavorite ? "currentColor" : "none"} stroke="currentColor" strokeWidth="2">
                      <path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"></path>
                    </svg>
                    <span className="btn-text">{recipe.isFavorite ? "Favorited" : "Favorite"}</span>
                  </button>

                  <button
                    className="icon-action-btn copy-btn"
                    onClick={(e) => handleCopyRecipe(e, recipe)}
                    title="Copy full recipe to clipboard"
                  >
                    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                      <rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
                      <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path>
                    </svg>
                    <span className="btn-text">{copiedId === (recipe._id || "current") ? "Copied! ✓" : "Copy"}</span>
                  </button>

                  <button
                    className="icon-action-btn print-btn"
                    onClick={(e) => handlePrintRecipe(e, recipe)}
                    title="Print recipe"
                  >
                    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                      <polyline points="6 9 6 2 18 2 18 9"></polyline>
                      <path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"></path>
                      <rect x="6" y="14" width="12" height="8"></rect>
                    </svg>
                    <span className="btn-text">Print</span>
                  </button>
                </div>
              </div>

              <div className="recipe-header">
                <h2>{recipe.name}</h2>
                {recipe.description && (
                  <p className="recipe-description">{recipe.description}</p>
                )}
                {recipe.createdAt && (
                  <p className="recipe-date-stamp">
                    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                      <circle cx="12" cy="12" r="10"></circle>
                      <polyline points="12 6 12 12 16 14"></polyline>
                    </svg>
                    Created: {formatRecipeDate(recipe.createdAt)}
                  </p>
                )}
              </div>

              {/* RECIPE META INFO */}
              <div className="recipe-info">
                <div className="meta-block">
                  <div className="meta-icon-wrapper">⏱️</div>
                  <div>
                    <span>Prep Time</span>
                    <strong>{recipe.prepTime || "N/A"}</strong>
                  </div>
                </div>

                <div className="meta-block">
                  <div className="meta-icon-wrapper">🔥</div>
                  <div>
                    <span>Cook Time</span>
                    <strong>{recipe.cookTime || "N/A"}</strong>
                  </div>
                </div>

                <div className="meta-block">
                  <div className="meta-icon-wrapper">🍽️</div>
                  <div>
                    <span>Servings</span>
                    <strong>{recipe.servings || "N/A"}</strong>
                  </div>
                </div>

                <div className="meta-block">
                  <div className="meta-icon-wrapper">⚡</div>
                  <div>
                    <span>Difficulty</span>
                    <strong>{recipe.difficulty || "N/A"}</strong>
                  </div>
                </div>
              </div>

              {/* RECIPE INGREDIENTS & INSTRUCTIONS */}
              <div className="recipe-body">
                <div className="ingredients">
                  <div className="section-title-wrap">
                    <h3>Ingredients</h3>
                    <span className="count-pill">{recipe.ingredients?.length || 0} items</span>
                  </div>

                  <ul className="ingredients-list">
                    {recipe.ingredients?.map((item, index) => (
                      <li key={index}>
                        <span className="bullet-check">✓</span>
                        <span className="ingredient-text">{item}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                <div className="instructions">
                  <div className="section-title-wrap">
                    <h3>Step-by-Step Instructions</h3>
                    <span className="count-pill">{recipe.instructions?.length || 0} steps</span>
                  </div>

                  <ol className="instructions-list">
                    {recipe.instructions?.map((step, index) => (
                      <li key={index}>
                        <div className="step-content">
                          <p>{step}</p>
                        </div>
                      </li>
                    ))}
                  </ol>
                </div>
              </div>

              {/* TIPS */}
              {recipe.tips?.length > 0 && (
                <div className="tips">
                  <div className="tips-title">
                    <span className="tips-icon">💡</span>
                    <h3>Chef's Pro Tips</h3>
                  </div>

                  <ul>
                    {recipe.tips.map((tip, index) => (
                      <li key={index}>{tip}</li>
                    ))}
                  </ul>
                </div>
              )}

              <div className="recipe-card-footer no-print">
                <button
                  className="another-button"
                  onClick={() => {
                    setRecipe(null);
                    setDish("");
                    setError("");
                    window.scrollTo({
                      top: 0,
                      behavior: "smooth",
                    });
                  }}
                >
                  <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                    <path d="M12 5v14M5 12h14"></path>
                  </svg>
                  Generate Another Recipe
                </button>
              </div>
            </div>
          </section>
        )}

        {/* SAVED RECIPES SECTION / DASHBOARD */}
        <section className="saved-recipes-section" id="saved-recipes">
          <div className="saved-recipes-container">
            <div className="section-header-row">
              <div>
                <p className="recipe-label">RECIPE DASHBOARD</p>
                <h2>Recipe History</h2>
                <p className="section-subtitle">
                  Browse, search, favorite, and manage your past AI-generated recipes stored securely in MongoDB.
                </p>
              </div>

              {/* Tab Filters */}
              <div className="filter-tabs">
                <button
                  className={`tab-btn ${filterMode === "all" ? "active" : ""}`}
                  onClick={() => setFilterMode("all")}
                >
                  All Recipes
                  <span className="tab-count">{savedRecipes.length}</span>
                </button>
                <button
                  className={`tab-btn ${filterMode === "favorites" ? "active" : ""}`}
                  onClick={() => setFilterMode("favorites")}
                >
                  Favorites ❤️
                  <span className="tab-count">{favoritesCount}</span>
                </button>
              </div>
            </div>

            {/* SEARCH AND CONTROLS BAR */}
            <div className="search-control-bar">
              <div className="search-input-box">
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <circle cx="11" cy="11" r="8"></circle>
                  <line x1="21" y1="21" x2="16.65" y2="16.65"></line>
                </svg>
                <input
                  type="text"
                  placeholder="Search saved recipes by title or description..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                />
                {searchQuery && (
                  <button
                    className="clear-search-btn"
                    onClick={() => setSearchQuery("")}
                    title="Clear search"
                  >
                    ✕
                  </button>
                )}
              </div>

              <div className="search-meta">
                <span>
                  Showing <strong>{filteredRecipes.length}</strong> of {savedRecipes.length} recipes
                </span>
              </div>
            </div>

            {/* Error loading saved recipes */}
            {fetchError && (
              <div className="fetch-error-box">
                <p>{fetchError}</p>
                <button className="retry-btn" onClick={fetchSavedRecipes}>
                  Retry Loading
                </button>
              </div>
            )}

            {/* Loading Skeleton */}
            {savedLoading ? (
              <div className="saved-recipes-grid">
                {[1, 2, 3].map((n) => (
                  <div className="saved-recipe-card skeleton-card" key={n}>
                    <div className="skeleton skeleton-title"></div>
                    <div className="skeleton skeleton-text"></div>
                    <div className="skeleton skeleton-text short"></div>
                    <div className="skeleton-tags">
                      <div className="skeleton skeleton-tag"></div>
                      <div className="skeleton skeleton-tag"></div>
                      <div className="skeleton skeleton-tag"></div>
                    </div>
                  </div>
                ))}
              </div>
            ) : filteredRecipes.length === 0 ? (
              /* EMPTY STATES */
              <div className="empty-state-card">
                {searchQuery ? (
                  <>
                    <div className="empty-icon">🔍</div>
                    <h3>No recipes found</h3>
                    <p>
                      No saved recipes matched your search for "<strong>{searchQuery}</strong>".
                    </p>
                    <button className="primary-empty-btn" onClick={() => setSearchQuery("")}>
                      Clear Search
                    </button>
                  </>
                ) : filterMode === "favorites" ? (
                  <>
                    <div className="empty-icon">❤️</div>
                    <h3>No favorite recipes yet</h3>
                    <p>
                      Click the heart icon on any saved recipe card to keep your absolute favorites handy here!
                    </p>
                    <button className="primary-empty-btn" onClick={() => setFilterMode("all")}>
                      View All Saved Recipes
                    </button>
                  </>
                ) : (
                  <>
                    <div className="empty-icon">📖</div>
                    <h3>No saved recipes yet</h3>
                    <p>
                      Enter your favorite dish in the generator above to create and save your first recipe to MongoDB!
                    </p>
                    <button
                      className="primary-empty-btn"
                      onClick={() => {
                        window.scrollTo({ top: 0, behavior: "smooth" });
                        const input = document.querySelector(".input-field-container input");
                        if (input) input.focus();
                      }}
                    >
                      Generate Your First Recipe
                    </button>
                  </>
                )}
              </div>
            ) : (
              /* SAVED RECIPES GRID */
              <div className="saved-recipes-grid">
                {filteredRecipes.map((item) => (
                  <div
                    className="saved-recipe-card"
                    key={item._id}
                    onClick={() => setSelectedRecipe(item)}
                  >
                    <div className="saved-card-header">
                      <div className="card-title-wrap">
                        <span className="card-date-badge">
                          <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                            <circle cx="12" cy="12" r="10"></circle>
                            <polyline points="12 6 12 12 16 14"></polyline>
                          </svg>
                          {formatRecipeDate(item.createdAt)}
                        </span>
                        <h3>{item.name}</h3>
                      </div>

                      {/* Favorite Button on Card */}
                      <button
                        className={`card-heart-btn ${item.isFavorite ? "active" : ""}`}
                        onClick={(e) => handleToggleFavorite(e, item)}
                        title={item.isFavorite ? "Remove favorite" : "Add to favorites"}
                        aria-label="Toggle favorite"
                      >
                        <svg width="18" height="18" viewBox="0 0 24 24" fill={item.isFavorite ? "currentColor" : "none"} stroke="currentColor" strokeWidth="2">
                          <path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"></path>
                        </svg>
                      </button>
                    </div>

                    <p className="saved-card-desc">
                      {item.description || "No description provided."}
                    </p>

                    <div className="saved-recipe-info">
                      {item.prepTime && <span>⏱️ {item.prepTime}</span>}
                      {item.cookTime && <span>🔥 {item.cookTime}</span>}
                      {item.difficulty && (
                        <span className={`diff-pill diff-${item.difficulty.toLowerCase()}`}>
                          {item.difficulty}
                        </span>
                      )}
                    </div>

                    <div className="saved-card-footer">
                      <button
                        className="view-recipe-btn"
                        onClick={(e) => {
                          e.stopPropagation();
                          setSelectedRecipe(item);
                        }}
                      >
                        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                          <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path>
                          <circle cx="12" cy="12" r="3"></circle>
                        </svg>
                        View Recipe
                      </button>

                      <div className="card-sub-actions">
                        <button
                          className="sub-action-btn"
                          onClick={(e) => handleCopyRecipe(e, item)}
                          title="Copy recipe text"
                        >
                          <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                            <rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
                            <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path>
                          </svg>
                        </button>

                        <button
                          className="sub-action-btn delete-btn"
                          onClick={(e) => {
                            e.stopPropagation();
                            setDeleteConfirmId(item._id);
                          }}
                          title="Delete recipe"
                        >
                          <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                            <polyline points="3 6 5 6 21 6"></polyline>
                            <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path>
                          </svg>
                        </button>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </section>
      </main>

      {/* VIEW FULL RECIPE MODAL */}
      {selectedRecipe && (
        <div
          className="modal-overlay"
          onClick={() => setSelectedRecipe(null)}
          role="dialog"
          aria-modal="true"
          aria-labelledby="modal-recipe-title"
        >
          <div
            className="modal-card"
            onClick={(e) => e.stopPropagation()}
          >
            {/* Modal Header */}
            <div className="modal-header">
              <div className="modal-header-left">
                <span className="recipe-label">FULL RECIPE DETAILS</span>
                <h2 id="modal-recipe-title">{selectedRecipe.name}</h2>
                <div className="modal-meta-row">
                  <span className="modal-date-tag">
                    <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                      <circle cx="12" cy="12" r="10"></circle>
                      <polyline points="12 6 12 12 16 14"></polyline>
                    </svg>
                    Saved: {formatRecipeDate(selectedRecipe.createdAt)}
                  </span>
                  {selectedRecipe.difficulty && (
                    <span className={`difficulty-tag difficulty-${selectedRecipe.difficulty.toLowerCase()}`}>
                      {selectedRecipe.difficulty}
                    </span>
                  )}
                </div>
              </div>

              <div className="modal-header-actions">
                <button
                  className={`modal-action-btn ${selectedRecipe.isFavorite ? "active" : ""}`}
                  onClick={(e) => handleToggleFavorite(e, selectedRecipe)}
                  title={selectedRecipe.isFavorite ? "Remove favorite" : "Add to favorites"}
                >
                  <svg width="18" height="18" viewBox="0 0 24 24" fill={selectedRecipe.isFavorite ? "currentColor" : "none"} stroke="currentColor" strokeWidth="2">
                    <path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"></path>
                  </svg>
                  <span>{selectedRecipe.isFavorite ? "Favorited" : "Favorite"}</span>
                </button>

                <button
                  className="modal-action-btn"
                  onClick={(e) => handleCopyRecipe(e, selectedRecipe)}
                  title="Copy recipe text"
                >
                  <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
                    <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path>
                  </svg>
                  <span>{copiedId === selectedRecipe._id ? "Copied! ✓" : "Copy"}</span>
                </button>

                <button
                  className="modal-action-btn"
                  onClick={(e) => handlePrintRecipe(e, selectedRecipe)}
                  title="Print recipe"
                >
                  <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <polyline points="6 9 6 2 18 2 18 9"></polyline>
                    <path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"></path>
                    <rect x="6" y="14" width="12" height="8"></rect>
                  </svg>
                  <span>Print</span>
                </button>

                <button
                  className="modal-close-btn"
                  onClick={() => setSelectedRecipe(null)}
                  aria-label="Close modal"
                  title="Close (Esc)"
                >
                  ✕
                </button>
              </div>
            </div>

            {/* Modal Scrollable Body */}
            <div className="modal-body">
              {selectedRecipe.description && (
                <p className="modal-recipe-desc">{selectedRecipe.description}</p>
              )}

              {/* Meta metrics */}
              <div className="recipe-info modal-recipe-info">
                <div className="meta-block">
                  <div className="meta-icon-wrapper">⏱️</div>
                  <div>
                    <span>Prep Time</span>
                    <strong>{selectedRecipe.prepTime || "N/A"}</strong>
                  </div>
                </div>

                <div className="meta-block">
                  <div className="meta-icon-wrapper">🔥</div>
                  <div>
                    <span>Cook Time</span>
                    <strong>{selectedRecipe.cookTime || "N/A"}</strong>
                  </div>
                </div>

                <div className="meta-block">
                  <div className="meta-icon-wrapper">🍽️</div>
                  <div>
                    <span>Servings</span>
                    <strong>{selectedRecipe.servings || "N/A"}</strong>
                  </div>
                </div>

                <div className="meta-block">
                  <div className="meta-icon-wrapper">⚡</div>
                  <div>
                    <span>Difficulty</span>
                    <strong>{selectedRecipe.difficulty || "N/A"}</strong>
                  </div>
                </div>
              </div>

              {/* Ingredients & Instructions */}
              <div className="recipe-body modal-recipe-body">
                <div className="ingredients">
                  <div className="section-title-wrap">
                    <h3>Ingredients</h3>
                    <span className="count-pill">{selectedRecipe.ingredients?.length || 0} items</span>
                  </div>

                  <ul className="ingredients-list">
                    {selectedRecipe.ingredients?.map((item, index) => (
                      <li key={index}>
                        <span className="bullet-check">✓</span>
                        <span className="ingredient-text">{item}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                <div className="instructions">
                  <div className="section-title-wrap">
                    <h3>Instructions</h3>
                    <span className="count-pill">{selectedRecipe.instructions?.length || 0} steps</span>
                  </div>

                  <ol className="instructions-list">
                    {selectedRecipe.instructions?.map((step, index) => (
                      <li key={index}>
                        <div className="step-content">
                          <p>{step}</p>
                        </div>
                      </li>
                    ))}
                  </ol>
                </div>
              </div>

              {/* Tips */}
              {selectedRecipe.tips?.length > 0 && (
                <div className="tips modal-tips">
                  <div className="tips-title">
                    <span className="tips-icon">💡</span>
                    <h3>Chef's Cooking Tips</h3>
                  </div>

                  <ul>
                    {selectedRecipe.tips.map((tip, index) => (
                      <li key={index}>{tip}</li>
                    ))}
                  </ul>
                </div>
              )}
            </div>

            {/* Modal Footer */}
            <div className="modal-footer">
              <button
                className="modal-delete-btn"
                onClick={() => setDeleteConfirmId(selectedRecipe._id)}
              >
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <polyline points="3 6 5 6 21 6"></polyline>
                  <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path>
                </svg>
                Delete Recipe
              </button>

              <button
                className="modal-done-btn"
                onClick={() => setSelectedRecipe(null)}
              >
                Back to History
              </button>
            </div>
          </div>
        </div>
      )}

      {/* DELETE CONFIRMATION DIALOG */}
      {deleteConfirmId && (
        <div
          className="dialog-overlay"
          onClick={() => !isDeleting && setDeleteConfirmId(null)}
          role="alertdialog"
          aria-modal="true"
        >
          <div className="dialog-box" onClick={(e) => e.stopPropagation()}>
            <div className="dialog-icon-danger">
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M3 6h18M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2M10 11v6M14 11v6"></path>
              </svg>
            </div>
            <h3>Delete Recipe?</h3>
            <p>
              Are you sure you want to permanently delete this recipe from MongoDB? This action cannot be undone.
            </p>
            <div className="dialog-actions">
              <button
                className="dialog-cancel-btn"
                onClick={() => setDeleteConfirmId(null)}
                disabled={isDeleting}
              >
                Cancel
              </button>
              <button
                className="dialog-confirm-btn"
                onClick={() => handleDeleteRecipe(deleteConfirmId)}
                disabled={isDeleting}
              >
                {isDeleting ? "Deleting..." : "Yes, Delete Recipe"}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* FOOTER */}
      <footer>
        <div className="footer-content">
          <div className="footer-logo">
            Recipe<span>AI</span>
          </div>
          <p>© 2026 RecipeAI. Powered by Google Gemini AI & MongoDB.</p>
          <div className="footer-links">
            <a href="#home">Back to top ↑</a>
          </div>
        </div>
      </footer>
    </div>
  );
}

export default App;